services:
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=test
    image: mongo:focal
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
